### ISSUE TITLE
ios App freezes after running RNRestart.Restart();

### ISSUE THREAD

**Issue by Monir-Shembesh** [avishayil/react-native-restart#108]
Just as the title says, I am trying to restart my bundle but the app freezes for a long time then displays `time out waiting for invalidate packages`. what is weird that this happens when I run the project from XCODE on a real device only... but when I am running an emulator it works fine. Any idea?

**Comment by yousafglixentech** [comment]
Having the same issue

**Comment by MazenRefaat** [comment]
I'm having the same issue, any solution found yet?

**Comment by Monir-Shembesh** [comment]
Any Updates guys? did you find a solution?

**Comment by Gerlison** [comment]
On android I'm having a similar issue, I believe. When I run the command the app throws `error calling RTCEventEmitter.receiveTouches`.

**Comment by arundev-kv** [comment]
Update the version to the 0.0.13 solves the issue for me

**Comment by Gerlison** [comment]
For who's having troubles with android, I solved using a functino provided by CodePush. This library is based on it, so how I already was with CodePush in my project, I used itself.
`CodePush.RestartApp()` (remember to pass nothing as argument, if it's true, the app will not restart)

**Comment by mariomurrent-softwaresolutions** [comment]
Same here - hangs on iOS

**Comment by avishayil** [comment]
Can you please provide an example repo to investigate? And a list of actions?

**Comment by avishayil** [comment]
Just to clarify I don't have a real iOS device so I can't replicate this

**Comment by avishayil** [comment]
Based on some internet reading:
- https://github.com/facebook/react-native/issues/15941
- https://github.com/facebook/react-native/issues/19294
- https://stackoverflow.com/questions/46206867/timeout-waiting-for-modules-to-be-invalidated

It seems that the issue is not related to this library, but due to some styling issues. Since we don't render any UI component here, I don't see any case for this issue to happen due to the way the library functions.

Can you see if the problem still occur after you removed this library?

If there will be no new activity on this issue it will be closed.
